# Generated by Django 2.2.24 on 2022-12-05 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='birthday',
        ),
    ]
