# Generated by Django 2.2.24 on 2022-12-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_userdetail_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='birthday',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
