# Generated by Django 2.2.24 on 2022-12-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userdetail_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='total',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='gender',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
